# Generated by Django 3.1.2 on 2020-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of country')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
    ]
