# Generated by Django 3.1.2 on 2020-10-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201026_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.country'),
            preserve_default=False,
        ),
    ]
