# Generated by Django 3.1.2 on 2020-11-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0017_auto_20201108_1118'),
        ('accounts', '0004_account_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='topic_created',
            field=models.ManyToManyField(related_name='user_topic_created', to='discourse.Topic'),
        ),
    ]
