# Generated by Django 3.1.2 on 2020-11-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_topic_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='topic_created',
            new_name='topics_created',
        ),
    ]
