# Generated by Django 3.1.2 on 2020-11-28 14:51

import accounts.models_fields_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201108_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/user_avatars', validators=[accounts.models_fields_validators.image_size_limit], verbose_name='User avatar'),
        ),
    ]
