# Generated by Django 3.1.2 on 2020-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201108_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/user_avatars', verbose_name='User avatar'),
        ),
    ]
