# Generated by Django 3.1.2 on 2020-10-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-timestamp']},
        ),
    ]
