# Generated by Django 3.1.2 on 2020-10-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0002_auto_20201029_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='discourse.topic'),
            preserve_default=False,
        ),
    ]
