# Generated by Django 3.1.2 on 2020-11-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0006_auto_20201031_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
