# Generated by Django 3.1.2 on 2020-11-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0009_auto_20201104_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='who_liked',
        ),
    ]
