# Generated by Django 3.1.2 on 2020-11-05 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discourse', '0010_remove_comment_who_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='who_liked',
            field=models.ManyToManyField(blank=True, related_name='who_liked_c', to=settings.AUTH_USER_MODEL),
        ),
    ]
