# Generated by Django 3.1.2 on 2020-11-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0017_auto_20201108_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='month_of_publication',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='self_url',
            field=models.URLField(null=True),
        ),
    ]
