# Generated by Django 3.1.2 on 2020-11-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0019_topic_day_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='day_of_publication',
            field=models.IntegerField(null=True),
        ),
    ]
