# Generated by Django 3.1.2 on 2020-11-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0021_subjectoftopic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectOfTopic',
            new_name='TagOfTopic',
        ),
        migrations.RenameField(
            model_name='tagoftopic',
            old_name='topic',
            new_name='tag',
        ),
    ]
