# Generated by Django 3.1.2 on 2020-11-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0023_auto_20201110_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagoftopic',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagoftopic',
            name='topic',
        ),
        migrations.AddField(
            model_name='tagoftopic',
            name='name_of_tag',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, to='discourse.TagOfTopic'),
        ),
    ]
