# Generated by Django 3.1.2 on 2020-11-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0024_auto_20201110_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_section', models.CharField(max_length=100)),
                ('topics_included', models.ManyToManyField(blank=True, to='discourse.Topic')),
            ],
        ),
    ]
