# Generated by Django 3.1.2 on 2020-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0025_topicsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='main_sphere_of_topic',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
