# Generated by Django 3.1.2 on 2020-11-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0026_topic_main_sphere_of_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(to='discourse.TagOfTopic'),
        ),
    ]
