# Generated by Django 3.1.2 on 2020-11-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0027_auto_20201112_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsection',
            name='image_of_section',
            field=models.ImageField(blank=True, null=True, upload_to='discourse/section_images', verbose_name='Section image'),
        ),
    ]
