# Generated by Django 3.1.2 on 2020-11-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0028_topicsection_image_of_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
