# Generated by Django 3.1.2 on 2020-11-28 14:55

import discourse.models_fields_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0034_auto_20201122_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image_of_topic',
            field=models.ImageField(blank=True, null=True, upload_to='discourse/topic_images', validators=[discourse.models_fields_validators.image_size_limit], verbose_name='Topic image'),
        ),
    ]
